"""
User management schemas — admin-created reviewers, etc.
"""

from enum import Enum
from typing import Any, Optional

from pydantic import AliasChoices, BaseModel, ConfigDict, EmailStr, Field, field_validator


class ReviewerLifecycleStatus(str, Enum):
    """FSD account status after provisioning (and for display)."""

    ACTIVE = "ACTIVE"
    INVITED = "INVITED"
    EXPIRED = "EXPIRED"


class CreateReviewerRequest(BaseModel):
    """
    Admin creates a platform reviewer (FSD user profile + system reviewer role).

    The JSON key ``role`` is the **job / org role** (e.g. Manager), not the system RBAC
    value (always ``reviewer`` for this endpoint).

    ``status`` is lifecycle: **ACTIVE**, **INVITED**, or **EXPIRED**. **EXPIRED** blocks sign-in.
    """

    model_config = ConfigDict(populate_by_name=True)

    email: EmailStr
    first_name: str = Field(
        ...,
        min_length=1,
        max_length=120,
        alias="firstName",
        validation_alias=AliasChoices("firstName", "first_name"),
    )
    last_name: str = Field(
        ...,
        min_length=1,
        max_length=120,
        alias="lastName",
        validation_alias=AliasChoices("lastName", "last_name"),
    )
    job_title: str = Field(
        ...,
        min_length=1,
        max_length=120,
        description="Job / org role label (e.g. Manager, Senior Reviewer).",
        alias="role",
        validation_alias=AliasChoices("role", "jobTitle", "job_title"),
    )
    designation: str = Field(..., min_length=1, max_length=200)
    department: str = Field(..., min_length=1, max_length=200)
    username: str = Field(..., min_length=1, max_length=120)
    language: str = Field(
        ...,
        min_length=2,
        max_length=32,
        description="UI language code or label (e.g. en, en-US).",
    )
    time_zone: str = Field(
        ...,
        min_length=1,
        max_length=120,
        alias="timeZone",
        validation_alias=AliasChoices("timeZone", "time_zone"),
        description="IANA or display time zone for the account.",
    )
    lifecycle_status: ReviewerLifecycleStatus = Field(
        default=ReviewerLifecycleStatus.INVITED,
        alias="status",
        validation_alias=AliasChoices("status", "lifecycle_status", "lifecycleStatus"),
        description="ACTIVE, INVITED, or EXPIRED. New accounts are usually INVITED until onboarded.",
    )

    @field_validator("lifecycle_status", mode="before")
    @classmethod
    def coerce_lifecycle(cls, v: Any) -> Any:
        if isinstance(v, str):
            key = v.strip().upper()
            if key in ("ACTIVE", "INVITED", "EXPIRED"):
                return ReviewerLifecycleStatus[key]
        return v

    @field_validator("username")
    @classmethod
    def strip_username(cls, v: str) -> str:
        s = v.strip()
        if not s:
            raise ValueError("username must not be empty")
        return s


class CreateReviewerResponse(BaseModel):
    """Returned once; includes a one-time temporary password and stored profile fields."""

    model_config = ConfigDict(populate_by_name=True)

    id: str
    email: EmailStr
    first_name: str = Field(alias="firstName")
    last_name: str = Field(alias="lastName")
    job_title: str = Field(
        ...,
        alias="jobTitle",
        description="Job / org role from the request (FSD ``role`` / ``jobTitle``).",
    )
    designation: str
    department: str
    username: str
    language: str
    time_zone: str = Field(alias="timeZone")
    lifecycle_status: ReviewerLifecycleStatus = Field(alias="status")
    role: str = "reviewer"
    requires_password_change: bool = Field(alias="requiresPasswordChange", default=True)
    is_first_login: bool = Field(alias="isFirstLogin", default=True)
    temporary_password: str = Field(
        ...,
        alias="temporaryPassword",
        description=(
            "One-time password generated by the server (never send a password in the request). "
            "Shown only in this response; user must change it and complete MFA."
        ),
    )


class CreateReviewerUserApiResponse(BaseModel):
    """OpenAPI-typed wrapper so Swagger shows every field under ``data`` (not ``object``)."""

    success: bool = True
    message: Optional[str] = None
    data: CreateReviewerResponse
